Repository eszegabor/KEK-Backend, pull requests merged in 2024-04, with the labels that each got.

#6 user interface modositasa
  src/user/address.dto.ts
  src/user/address.interface.ts
  src/user/address.schema.ts
  src/user/match.decorator.ts
  src/user/user.dto.ts
  src/user/user.interface.ts
Labels: EG

#8 user sema javitas
  src/user/user.model.ts
Labels: EG

#10 Issue Title user dokumentacio
  src/authentication/authentication.controller.ts
  src/authentication/logIn.dto.ts
  src/server.ts
  src/user/user.model.yml
Labels: EG

#11 swagger url javitasa
  src/authentication/authentication.controller.ts
Labels: documentation, EG

#12 URL javitasa
  src/authentication/authentication.controller.ts
Labels: documentation, EG

#13 e-mail cim ellenorzes kikapcsolasa
  src/authentication/authentication.controller.ts
Labels: bug, NL

#15 order controller
  src/order/order.dto.ts
  src/order/order.interface.ts
  src/order/order.model.ts
  src/order/orderProduct.interface.ts
Labels: enhancement, NL

#17 setup sendgrid for e-mail verification
  package.json
  src/authentication/authentication.controller.ts
  src/order/order.model.ts
  src/user/user.dto.ts
Labels: bug, NL

#18 offer*interfacek letrehozasa
  src/offer/offer.interface.ts
  src/offer/offeringProduct.interface.ts
Labels: EG

#19 user controller dokumentalasa
  src/order/order.model.ts
  src/order/order.model.yml
  src/user/user.controller.ts
  src/user/user.controller.yml
  src/user/user.model.ts
Labels: enhancement, NL

#20 localhost *.bat torles
  data/import_posts_to_localhost.bat
  data/import_recipes_to_localhost.bat
  data/import_users_to_localhost.bat
Labels: bug, NL

#22 users tabla mongoexport es import javitasa
  data/export_users_from_atlas.bat
  data/import_users_to_atlas.bat
  data/users.json
Labels: bug, NL

#24 order model es controller
  src/exceptions/OrderNotFound.exception.ts
  src/order/order.controller.ts
  src/order/order.controller.yml
  src/order/order.dto.ts
  src/order/order.interface.ts
  src/order/order.model.ts
  src/order/order.model.yml
  src/order/orderDetail.interface.ts
  src/order/orderDetail.model.yml
  src/order/orderDetail.schema.ts
Labels: enhancement, NL

#27 order controller fejlesztese
  src/order/order.controller.ts
  src/order/order.controller.yml
Labels: enhancement, NL

#28 order controller javitasa
  src/order/order.controller.ts
  src/order/order.model.yml
  src/order/orderDetail.interface.ts
  src/order/orderDetail.schema.ts
  src/order/orderDetail.schema.yml
Labels: bug, enhancement, NL

#29 offering controller letrehozasa
  .vscode/settings.json
  src/offer/offer.controller.ts
  src/offer/offer.controller.yml
  src/offer/offerDetail.interface.ts
  src/offer/offerDetail.schema.ts
  src/offer/offerDetail.schema.yml
  src/offer/offering.dto.ts
  src/offer/offering.interface.ts
  src/offer/offering.model.ts
  src/offer/offering.model.yml
  src/server.ts
Labels: enhancement, EG
