Repository eszegabor/KEK-Backend, pull requests merged in 2024-05, with the labels that each got.

#30 offer controller modositas
  src/exceptions/OfferNotFount.exception.ts
  src/offer/offer.controller.ts
Labels: EG

#32 Esze-gabor
  src/offer/offer.controller.ts
  src/offer/offer.controller.yml
Labels: EG

#33 todo.txt letrehozasa
  data/users.json
  src/todo.txt
Labels: documentation, NL

#35 Esze-gabor
  data/export_offers_from_atlas.bat
  data/import_offers_to_atlas.bat
  data/offers.json
  src/offer/offer.controller.ts
  src/offer/offer.controller.yml
  src/offer/offer.test.ts
Labels: documentation, EG

#37 products controller
  data/import_products_to_atlas.bat
  data/products.json
  src/exceptions/ProductNotFound.exception.ts
  src/product/product.controller.ts
  src/product/product.dto.ts
  src/product/product.interface.ts
  src/product/product.model.ts
  src/server.ts
Labels: enhancement, HG
