Repository eszegabor/KEK-Backend, pull requests merged in 2024-06, with the labels that each got.

#38 order controller modositasa
  data/import_products_to_atlas.bat
  src/exceptions/UserIdCannotChangeException.ts
  src/order/order.controller.ts
Labels: enhancement

#39 3-5 product-ok hozzáadása
  data/products.json
Labels: enhancement

#40 tovabbi 5 gyumolcs hozzaadasa
  data/products.json
Labels: enhancement, NL

#42 cyclic-render csere
  README.md
  dist/authentication/__tesztek__/authentication.teszt.js
  dist/authentication/__tesztek__/authentication.teszt.js.map
  dist/authentication/authentication.controller.js
  dist/exceptions/ProductNotFound.exception.js
  dist/exceptions/ProductNotFound.exception.js.map
  dist/exceptions/UserIdCannotChangeException.js
  dist/exceptions/UserIdCannotChangeException.js.map
  dist/order/__tests__/order.test.js
  dist/order/__tests__/order.test.js.map
  dist/product/product.controller.js
  dist/product/product.controller.js.map
  dist/product/product.dto.js
  dist/product/product.dto.js.map
  dist/product/product.interface.js
  dist/product/product.interface.js.map
  dist/product/product.model.js
  dist/product/product.model.js.map
  dist/recipe/__tesztek__/recipe.teszt.js
  dist/recipe/__tesztek__/recipe.teszt.js.map
  src/authentication/authentication.controller.ts
  src/openapi.yaml.old
  src/swagger.json.old
Labels: bug, NL

#43 rename app to com
  .eslintrc.js
  .vscode/settings.json
  README.md
  dist/authentication/authentication.controller.js
  src/authentication/authentication.controller.ts
  src/openapi.yaml.old
  src/swagger.json.old
Labels: bug

#44 order controller javitasa
  src/exceptions/Http.exception.ts
  src/exceptions/Http.exception.yml
  src/exceptions/OrderDetailNotFound.exception.ts
  src/order/order.controller.ts
  src/order/order.controller.yml
  src/order/order.model.yml
Labels: NL, bug enhancement

#45 remove server from order yml
  src/order/order.controller.yml
Labels: NL, bug enhancement

#47 rendrakas
  data/export_posts_from_atlas.bat
  data/import_posts_to_atlas.bat
  data/orders_new.json
  data/posts.json
  help/email_verification/Brevo - CRM Suite.url
  help/email_verification/Crypto - Node.js v21.6.2 Documentation.url
  help/email_verification/Email Verification using SendGrid in Node.js, Express.js & MongoDB - by Sohan Lal Gupta - Medium - Medium.url
  help/email_verification/Email Verification with Nodemailer using Express.js, Sequelize, and PostgreSQL - by Racheal Kuranchie - Medium.url
  help/email_verification/How to Send SMTP Emails in Node.js With SendGrid.url
  help/email_verification/Mailtrap- Email Delivery Platform.url
  help/email_verification/handlebars - npm.url
  help/email_verification/nodemailer - npm.url
Labels: enhancement, NL
